services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - finance-network
    volumes:
      - zookeeper-data:/var/lib/zookeeper  # Adding volume for Zookeeper data

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - finance-network
    volumes:
      - kafka-data:/var/lib/kafka/data  # Adding volume for Kafka data

  postgres-financesystemdb:
    image: postgres:15-alpine
    container_name: postgres-financesystemdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: centralizedfinancedb
    volumes:
      - postgres-financesystem-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - finance-network

  financesystem-service:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    container_name: financesystem-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-financesystemdb:5432/centralizedfinancedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - finance-network
    depends_on:
      - kafka
      - postgres-financesystemdb

networks:
  finance-network:
    driver: bridge

volumes:
  postgres-financesystem-data:
  kafka-data:
  zookeeper-data:
